# See the following for information on how to setup the Python workflow for a
# single version:
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Validation Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    # See https://github.com/actions/checkout#Checkout-multiple-repos-side-by-side
    steps:
    - name: Checkout AceTime
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout UnixHostDuino
      uses: actions/checkout@v2
      with:
        repository: bxparks/UnixHostDuino
        path: UnixHostDuino

    - name: Checkout AUnit
      uses: actions/checkout@v2
      with:
        repository: bxparks/AUnit
        path: AUnit

    - name: Checkout IANA tz
      uses: actions/checkout@v2
      with:
        repository: eggert/tz
        path: tz

    - name: Checkout Hinnant date
      uses: actions/checkout@v2
      with:
        repository: HowardHinnant/date
        path: date

    - name: Install libcurl4-openssl-dev
      run: |
        sudo apt update
        sudo apt install -y libcurl4-openssl-dev

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r AceTime/tools/requirements.txt

    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: '>=11.0.8'

    - name: Build compare_cpp
      run: |
        cd AceTime/tools/compare_cpp
        make

    - name: Build compare_java
      run: |
        cd AceTime/tools/compare_java
        make

    - name: Build Validation Tests
      run: |
        make -C AceTime/tests/validation tests

    - name: Run Validation Tests
      run: |
        make -C AceTime/tests/validation runtests
